# user-config-template.yml for user - {{.UserName}}
upstream_dns_servers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
permanent_dns_servers:
  - "95.85.95.85:53"
  - "2.56.220.2:53"
load_balancing_strategy: "robin"
# If first available upstream server strategy enabled set to true if another strategy selected set to false
first_available_enabled: false
# Check first available upstream server every N seconds
first_available_duration: 5s
# Bootstrap / Fallback DNS server
bootstrap_dns_servers:
  - "208.67.222.222:53"
  - "208.67.220.220:53"
  - "1.1.1.1:53"
  - "2.56.220.2:53"
# Domain for upstream availability checking
check_available_domain: "openbld.net."
allowed_qtypes:
  - A
  - AAAA
  - CNAME
  - HTTPS
use_local_hosts: true
use_remote_hosts: true
permanent_enabled: true
hosts_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zbld/master/block.txt"
permanent_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zbld/master/allow.txt"
reload_interval_duration: 1h
default_ip_address: "0.0.0.0"
enable_dns_tcp: true
console_message_enabled: true
console_message: "- Blocked by zBLD"
enable_logging: true
enable_console_logging: true
log_store_duration: 24h
# Note: Not change this parameter
log_dir: "users/logs"
cache_enabled: true
cache_ttl_seconds: 3600
cache_clean_duration: 12h
metrics_enabled: true
# Prometheus top name increment after N requests for unique domains
prom_top_name_inc_after: 100
# Individual parameters for each user
dns_port: {{.DNSPort}}
metrics_port: {{.MetricsPort}}
log_file: "{{.LogFile}}"
config_version: "{{.ConfigVersion}}"
user_name: "{{.UserName}}"
user_alias: "{{.UserAlias}}"
user_comment: "{{.UserComment}}"
# Modes
inverse: true
# Extra settings
is_debug: false
truncate_messages: false