# user-config-template.yml for user - {{.UserName}}
upstream_dns_servers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
permanent_dns_servers:
  - "95.85.95.85:53"
  - "2.56.220.2:53"
load_balancing_strategy: "robin"
allowed_qtypes:
  - A
  - AAAA
  - CNAME
  - HTTPS
  - NS
  - PTR
use_local_hosts: true
use_remote_hosts: true
permanent_enabled: true
hosts_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zdns/master/block.txt"
permanent_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zdns/master/allow.txt"
reload_interval_duration: 1h
default_ip_address: "0.0.0.0"
enable_logging: true
cache_enabled: true
cache_ttl_seconds: 3600
metrics_enabled: true
# Individual parameters for each user
dns_port: {{.DNSPort}}
metrics_port: {{.MetricsPort}}
log_file: "{{.LogFile}}"
config_version: "{{.ConfigVersion}}"
user_name: "{{.UserName}}"
user_alias: "{{.UserAlias}}"
user_comment: "{{.UserComment}}"
# Modes
inverse: true
is_debug: false