upstream_dns_servers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
# Load balancing strategies robin, strict. Default is robin
load_balancing_strategy: "robin"
hosts_file: "hosts.txt"
default_ip_address: "0.0.0.0"
dns_port: 5001
enable_logging: true
# If inverse is set to true, then the hosts file will be treated as a blacklist
inverse: false
# If enable_cache is set to true, then the results of DNS queries will be cached
cache_enabled: true
# Stale cache entries will be removed after this many seconds
cache_ttl_seconds: 3600