# Upstreams settings
# Load balancing strategies robin, strict. Default is robin
load_balancing_strategy: "robin"
# Default upstreams for not permanent domains
upstream_dns_servers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
# Upstream DNS servers for permanent whitelisted domains
permanent_dns_servers:
  - "95.85.95.85:53"
  - "2.56.220.2:53"
# Allowed query types
allowed_qtypes:
  - A
  - AAAA
  - HTTPS
  - CNAME
#  - NS
#  - PTR
#  - SRV
#  - SOA
#  - TXT
#  - MX
# Not implemented yet
#  - NAPTR
#  - DS
#  - DNSKEY
#  - RRSIG
#  - CAA
#  - TLSA
#  - ANY
#  - AXFR
#  - IXFR
#  - OPT

# Hosts files settings
# Default hosts file (if inverse false - allow, if inverse true - block)
hosts_file: "hosts.txt"
# Plain text and /regex/ hosts file supported
hosts_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zbld/master/block.txt"
# Permanent - everything allowed
permanent_whitelisted: "hosts-permanent.txt"
permanent_file_url:
  - "https://raw.githubusercontent.com/m0zgen/my-zbld/master/allow.txt"
permanent_enabled: true
# Remote and local host files reload interval
reload_interval_duration: 1h
# Enable/Disable local and remote hosts files loading
use_local_hosts: true
use_remote_hosts: true

# DNS server settings
# Local DNS server port
dns_port: 50000
# Enable DNS tcp server (udp enabled by default)
enable_dns_tcp: true

# Settings for blocked domains
# Default respond for blocked domains
default_ip_address: "0.0.0.0"
# Console TXT message for blocked domain (for nslookup etc.)
console_message_enabled: true
console_message: "- Domain blocked by zBLD. Client IP:"

# Logging settings
# Enable/Disable logging to file
enable_logging: true
# Show messages in console (false: discard, true: show)
enable_console_logging: true
# Duration hours for log files (maxAge)
log_store_duration: 24h
log_dir: "users/logs"
# Log file prefix
log_file: "zbld_root"

# Cache settings
# If enable_cache is set to true, then the results of DNS queries will be cached
cache_enabled: true
# Stale cache entries will be removed after this many seconds
cache_ttl_seconds: 3600

# Prometheus Metrics
metrics_enabled: true
metrics_port: 40000
# Extra metrics settings
# Prometheus top name increment after N requests for unique domains
prom_top_name_inc_after: 100

# Users management
user_hosts_template: "addits/templates/user-hosts.txt"
user_hosts_permanent_template: "addits/templates/user-hosts-permanent.txt"
user_config_template: "addits/templates/user-config.yml"
users_dir: "users"
users_log_dir: "users/logs"
# If user does not exist in the system, then will set permissions for current user
user_dir_permission_for: "zbld"

# Modes
# Inverse settings
# If inverse is set to true, then the hosts files from hosts_file, hosts_file_url will be treated as a blacklist
# instead of a whitelist (if false). In short, if true, then the hosts file will be marked as blacklisted
inverse: true
# Extra options
is_debug: false
# Truncate DNS messages if over 512 bytes (for main servers - true)
truncate_messages: false

# Config version
config_version: "Root-0.3.0"