upstream_dns_servers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
allowed_qtypes:
  - A
  - AAAA
  - CNAME
  - NS
#  - MX
#  - SRV
  - PTR
#  - SOA
#  - TXT
# Not implemented yet
#  - NAPTR
#  - DS
#  - DNSKEY
#  - RRSIG
#  - CAA
#  - TLSA
#  - ANY
#  - AXFR
#  - IXFR
#  - OPT
# Load balancing strategies robin, strict. Default is robin
load_balancing_strategy: "robin"
hosts_file: "hosts.txt"
use_local_hosts: true
use_remote_hosts: true
# Plain text and /regex/ hosts file supported
hosts_file_url:
  - "https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt"
  - "https://raw.githubusercontent.com/m0zgen/dns-hole/master/regex/common-wl.txt"
# Remote and local host files reload interval
reload_interval_duration: 1h
# Default respond for restricted domains
default_ip_address: "0.0.0.0"
dns_port: 50000
enable_logging: true
log_file: "zdns.log"
# If inverse is set to true, then the hosts file will be treated as a blacklist
# instead of a whitelist. In short, if true, then the hosts file will be marked as blacklisted
inverse: false
# If enable_cache is set to true, then the results of DNS queries will be cached
cache_enabled: true
# Stale cache entries will be removed after this many seconds
cache_ttl_seconds: 3600
# Metrics enabled
metrics_enabled: true
metrics_port: 40000
is_debug: false
# Extra options
permanent_enabled: true
permanent_whitelisted: "hosts-permanent.txt"
# Upstream DNS servers for permanent whitelisted domains
permanent_dns_servers:
  - "95.85.95.85:53"
  - "2.56.220.2:53"
# Config version
config_version: "0.2.2"
# Users management
user_hosts_template: "addits/templates/user-hosts.txt"
user_hosts_permanent_template: "addits/templates/user-hosts-permanent.txt"
user_config_template: "addits/templates/user-config.yml"
users_dir: "users"
users_log_dir: "users/logs"